### PR TITLE
Reactive margin modification.

### PR DESCRIPTION
**Pull request by Jungyeong-Eom**
I have just modified input-container and textarea's margin value on web_chat.html and week1-day4-assignment.html.

### CODE REVIEW

**Review by ggiande — COMMENTED** [review]
Are the input container and text area both necessary?

**Comment by Jungyeong-Eom** [comment]
Input container is necessary but, text area isn't.

**Comment by Jungyeong-Eom** [comment]
Actually, I got a problem in input container. When I resize it vertically, It becomes ugly.

**Comment by ggiande** [comment]
Ok! I think the next PR should address this issue. For the time being. I'll accept the review.

**Review by ggiande — APPROVED** [review]
No conflicts and the new site is responsive with some bugs that can be addressed at a later date.

**Pull request merged**
